### ISSUE TITLE
new Board() crashes if no detected port

### ISSUE THREAD

**Issue by jflamy** [nemikor-solutions/blue-owl-core#16]
To reproduce
```
            board = await connectBoard();
```
on Windows system with no physical Arduino (only virtual ports).  Or, I suspect, any machine with no connected Arduino.
Passing in a port normally works as long as serialPort is not undefined.
```
            board = await connectBoard({
                port: config.serialPort,
            });
``` 

A Workaround is to try/catch the error and provide a meaningful message if serialport is undefined.

TypeError: Cannot read properties of undefined (reading 'list')
    at Board.detect (C:\Dev\git\blue-owl\node_modules\johnny-five\lib\board.js:42:16)
    at new Board (C:\Dev\git\blue-owl\node_modules\johnny-five\lib\board.js:291:23)
    at exports.default (C:\Dev\git\blue-owl\src\lib\board.ts:10:19)
    at exports.default (C:\Dev\git\blue-owl\build-it-yourself\scripts\runner.ts:39:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jflamy** [comment]
This used to work - the j5 message about not finding a port would come up.  Perhaps related to the serialport upgrade.

**Comment by scottgonzalez** [comment]
Based on that error message, you're using an unmodified Johnny-Five with serialport 10. But we should still handle the case of an error being through during board instantiation.
